#!/bin/bash

# set -euf -o pipefail
set -o pipefail

URL="$1"
repo_name="$(basename "$URL" ".${URL##*.}")"
[ -n "$2" ] && repo_name="$2"

mkdir -p "$repo_name"
gixp \
    --progress \
    pack-receive "$URL" \
    --protocol 2 \
    --refs-directory "$repo_name" \
    "$repo_name"

mkdir -p "$repo_name/.git/objects/pack"
mv "$repo_name"/*.{pack,idx} "$repo_name/.git/objects/pack"
mv "$repo_name"/{HEAD,refs} "$repo_name/.git"

main_branch_name="$(git -C "$repo_name" remote show "$URL" | grep 'HEAD branch' | cut -d' ' -f5)"

git -C "$repo_name" checkout "$main_branch_name"

echo \
"[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote \"origin\"]
    url = $URL
    fetch = +refs/heads/*:refs/remotes/origin/*
[branch \"$main_branch_name\"]
    remote = origin
    merge = refs/heads/$main_branch_name
[pull]
    rebase = false" > "$repo_name"/.git/config



git -C "$repo_name" pull
